### ISSUE TITLE
Icon mis-alignments

### ISSUE THREAD

**Issue by amwx** [robloo/SymbolIconManager#1]
Hi!
I've been looking into the icon mis-alignment issue, and I can say it's not from the Viewbox. The Viewbox does have an issue with layout rounding, but otherwise it's working as it should.

So, I'm thinking its a combination of how the font is generated and how Avalonia's text system reads it. Comparing the checkmark glyph in Symbols to FluentSystemIcons using fontdrop, there are some notable differences
![image](https://user-images.githubusercontent.com/40413319/156270249-ff6ae183-e6ea-47e9-b568-1e0e5667d82f.png)

It seems FontForge is altering the path data (x/y min/max and the path data itself is different - along with the advance width and left side bearing). In FluentSystemIcons, the Baseline and Descender are in the same position, whereas in Symbols they're separate. So I'm wondering if these differences are leading to the alignment issues I've noticed? Not sure if this can be read from/set with FontForge so looking for some insight from you if A) this might be the reason, and B) if so, is it easily fixable.

**Comment by robloo** [comment]
Thanks for taking a more detailed look.

 1. My first guess is the baseline needs to be adjusted. FontForge defaults to 200px which can be seen in the left image. However, it should probably be at the very bottom (0px) like on the right. I'll have to read up on how to adjust that but it should be doable.
     * https://stackoverflow.com/questions/14813583/set-baseline-with-fontforge-scriping
 3. The overall size is also set by FontForge. It automatically imports SVG assuming 1000-by-1000. I don't think that can be changed before import. I'm not sure how difficult it is to change after SVG import is complete but according to the images it needs to be scaled from ~1000 to 500~ 2048 to match Segoe Fluent. Margins and alignment visually seem well enough though and it should scale the same in a viewbox.
     * Can likely be done with a scale matrix as in num.1
 5. As you also noted, the X coordinates (left side bearing) probably need to be adjusted as well. That is most difficult though and I'm not sure it can be done without some calculation based on the SVG which is currently out of scope.
    * https://www.iro.umontreal.ca/~boyer/typophile/doc/python.html


It might be this weekend before I have a more detailed look. FontForge docs are poor in this area.

**Comment by robloo** [comment]
I'll keep my first comment updated as the plan changes. But I think I have an idea for each change now. To answer your questions more directly:

 A. Yes, I think you found some issues here -- baseline being the most obvious
 B. It should be fixable, not sure how easy yet.

**Comment by amwx** [comment]
No problem and no rush. Thanks for your help on this. Hopefully this also benefits anybody using the non-custom version of the symbol font too.

**Comment by robloo** [comment]
@amwx I attempted to fix all the issues (except left side bearing). Could you give the below font a try with what you were testing when you noticed this issue and see if it's fixed? Based on my understanding it should work now.

[FluentAvalonia_Test1.zip](https://github.com/robloo/SymbolIconManager/files/8194358/FluentAvalonia_Test1.zip)

![image](https://user-images.githubusercontent.com/17993847/156959070-ce5cbba1-5f4e-40b3-af41-6d877de267bb.png)

**Comment by amwx** [comment]
@robloo 

Thanks again for looking into this. Unfortunately, I don't really see any changes. Looking at fontdrop, it looks like you've scaled the canvas to 2048x2048. Not sure if that was intentional or not - but that and the left side bearing probably aren't related to the alignment issue so that's fine.

Using the checkmark glyph...
Symbols - 14x15.25 glyph
Fluent - 14x14.14 glyph
So the new font is building just slightly taller than it is wide (and those dimensions match WPF). Just looking at a comparison between the two, it almost looks like the glyph is still being centered just above the center point and space is still added as if the baseline isn't zero (if that makes any sense)
![image](https://user-images.githubusercontent.com/40413319/156967587-74418e9b-24bf-48bd-98af-a33aaee9843b.png)

Is that file the full font file? I noticed there were several glyphs missing from it. Everything matching my Symbol enum was there, but none of the others to match Segoe Fluent were - (scroll carets, the icons for caption buttons, specifically).

I think I'm gonna go play with fontforge, and see if I can't wrap my mind around what's going on here.

**Comment by robloo** [comment]
Biggest issue I see is that it should be square. I'm not sure why it isn't.

> Unfortunately, I don't really see any changes

Ascent, Descent was modified so the baseline is now at zero instead of 200. That said, your screenshot looks OK. I was thinking it was appearing like below to you:

![image](https://user-images.githubusercontent.com/17993847/156970897-5b7964a2-0ab0-4d8a-a1b6-5a04ea74b8d0.png)

It doesn't seem that bad but I can see it still doesn't appear vertically aligned. It also may be an issue with the way Avalonia is calculating things. There are major rewrites in that area as you know and there are still bugs. (Unless you already checked with WPF which is what "So the new font is building just slightly taller than it is wide (and those dimensions match WPF)" may mean).

Keep in mind:

 1. the source glyphs do not appear to be perfectly aligned in the Fluent UI System. To fix that would require some additional calculation which may be possible with FontForge -- otherwise the SVG needs to be edited. I'm not sure it's really necessary though and it wouldn't explain what we are seeing here. (It would be a pixel or 2 at most).
 2. These are not the same glyphs as Windows Segoe Fluent. There are some notable differences. The biggest is that Windows glyphs are scaled so they have no margin. Fluent UI System has a margin. This means the Fluent UI system has smaller glyphs in appearance (line width, etc.).

> it looks like you've scaled the canvas to 2048x2048. Not sure if that was intentional or not

That is intentional. TrueType fonts should have an even power of 2 EM-size. it was either 1024 or 2048 (500 is incorrect in the Fluent UI System files). After checking Windows Segoe Fluent, they use 2048 so that is what I did here. The goal is to be compatible with the Windows font more than Fluent UI system.

> Is that file the full font file?

No, it isn't the full file. It is exactly what you discovered: Just for testing I only built the FluentAvalonia specific glyphs. I can build a full file if you need it.

> I think I'm gonna go play with fontforge,

Take a good look at the build script. I documented everything and the reasons why things are done the way they are:

https://github.com/robloo/SymbolIconManager/blob/5f343c6f1cfbced82c62194947db4d02b67b1ab8/Source/Models/FontBuilder.cs#L154

**Comment by amwx** [comment]
> Biggest issue I see is that it should be square. I'm not sure why it isn't.

Yes, I think that's the root problem here. 

> Ascent, Descent was modified so the baseline is now at zero instead of 200. That said, your screenshot looks OK. I was thinking it was appearing like below to you:
> 
> ![image](https://user-images.githubusercontent.com/17993847/156970897-5b7964a2-0ab0-4d8a-a1b6-5a04ea74b8d0.png)
> 
> It doesn't seem that bad but I can see it still doesn't appear vertically aligned. It also may be an issue with the way Avalonia is calculating things. There are major rewrites in that area as you know and there are still bugs. (Unless you already checked with WPF which is what "So the new font is building just slightly taller than it is wide (and those dimensions match WPF)" may mean).

It does still look the same as those buttons if you remove the Fluent comparison and the red background - the checkmark sits too high. I've checked with WPF and Avalonia's master branch for the new text stuff and it all basically rendering identically.

> Keep in mind:
> 
>     1. the source glyphs do not appear to be perfectly aligned in the Fluent UI System. To fix that would require some additional calculation which may be possible with FontForge -- otherwise the SVG needs to be edited. I'm not sure it's really necessary though and it wouldn't explain what we are seeing here. (It would be a pixel or 2 at most).

I don't think that's necessary to go that far into this. I think if we can figure out why the glyph isn't measuring square that will solve most of the problems here.


>     2. These are not the same glyphs as Windows Segoe Fluent. There are some notable differences. The biggest is that Windows glyphs are scaled so they have no margin. Fluent UI System has a margin. This means the Fluent UI system has smaller glyphs in appearance (line width, etc.).

Right. I'm not even comparing to Segoe Fluent, just the open source Fluent icons

> > it looks like you've scaled the canvas to 2048x2048. Not sure if that was intentional or not
> 
> That is intentional. TrueType fonts should have an even power of 2 EM-size. it was either 1024 or 2048 (500 is incorrect in the Fluent UI System files). After checking Windows Segoe Fluent, they use 2048 so that is what I did here. The goal is to be compatible with the Windows font more than Fluent UI system.
> 
> > Is that file the full font file?
> 
> No, it isn't the full file. It is exactly what you discovered: Just for testing I only built the FluentAvalonia specific glyphs. I can build a full file if you need it.

That's all fine. I just wanted to make sure I wasn't missing something.


I've opened the font in the fontforge desktop app, and everything looks ok there. The glyphs themselves are centered (visually) in the 2048x2048 canvas inside fontforge - so maybe it's something happening in the export process?

**Comment by robloo** [comment]
> It does still look the same as those buttons if you remove the Fluent comparison and the red background - the checkmark sits too high.

Well, horizontal alignment looked wrong there too. Maybe that was just your margins.

> I don't think that's necessary to go that far into this. I think if we can figure out why the glyph isn't measuring square that will solve most of the problems here.

Yep, agreed

> I've opened the font in the fontforge desktop app, and everything looks ok there. 

Yes, I double checked as well and couldn't find anything wrong. Perhaps something esoteric like the underline position is all I can think of.

> The glyphs themselves are centered (visually) in the 2048x2048 canvas inside fontforge

Yes, all previewers I've seen also render centered just fine. Avalonia is the only one that looks strange. I might play around with this in XAML directly later.

> so maybe it's something happening in the export process?

Well, since it looks fine opening the final font in FontForge that seems doubtful. Even if the build process was incorrect is should appear when we open the constructed font. I also checked this build process manually without using a python script -- it's how I discovered a few things. I don't think the python script is doing anything unintended.

**Comment by robloo** [comment]
It appears the OS/2 table metrics **May** be the issue. This is used on some platforms and FontForge has some strange defaults that don't match with the ascent/descent/em-size settings set elsewhere.

https://silnrsi.github.io/FDBP/en-US/Line_Metrics.html
https://docs.microsoft.com/en-us/typography/opentype/spec/os2
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html
https://simoncozens.github.io/fonts-and-layout/opentype.html#vertical-metrics-hhea-and-os2

Here is Windows Segoe Fluent:
![image](https://user-images.githubusercontent.com/17993847/156978766-e419a170-b70e-463d-a42d-f9bdd6d47678.png)

And here is the custom FluentAvalonia Font:
![image](https://user-images.githubusercontent.com/17993847/156978811-c593dde2-4b22-49ee-b4ff-f8ff59da34f4.png)

**Comment by robloo** [comment]
@amwx Here is a new test with the OS/2 table fixed (skipping some things like superscript/subscript metrics).

[FluentAvalonia_Test2.zip](https://github.com/robloo/SymbolIconManager/files/8195320/FluentAvalonia_Test2.zip)

**Comment by amwx** [comment]
That was it!
![image](https://user-images.githubusercontent.com/40413319/157122414-220e6f65-4543-4191-a85f-dbfcafdf5d35.png)

It's now rendering square, and is just about identical to Fluent System icons. If you remove the margins, it's also just about the same Segoe Fluent so the OS/2 settings were the problem.

The TaskDialog buttons also look much better now too
![image](https://user-images.githubusercontent.com/40413319/157122610-a81872ef-a29b-4f44-8147-fb103d8d8fdd.png)

**Comment by robloo** [comment]
Awesome! Good news :) That does look much better and am glad the solution is known.

Now I need to try to automate setting these properties in the build script. There are a few I couldn't find last night and am worried they aren't all available to python. Nevertheless, I'll see what I can do with this and then rebuild the complete font for you to test and hopefully update FluentAvalonia with.

**Comment by robloo** [comment]
FontForge doesn't seem to correctly support the properties I need to set for the metric tables. I opened a discussion on their repo https://github.com/fontforge/fontforge/discussions/4931 but there has been no response.

I think I'll just have to add a manual process in the font build process for the time being to close this out. When/if FontForge solves these issues I'll hopefully automate the entire build again.
